/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 src/models/spiderman.glb
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiderman-rigged-36c40fd392a64aaa935bae39070726bc
Title: Spiderman Rigged
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from '@react-three/drei';

export function Spiderman(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('src/models/spiderman.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.run.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="unamed" />
                  <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.CoC_iOS_HER_PPA_SEN_Bmat} skeleton={nodes.Object_6.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('src/models/spiderman.glb')

export default Spiderman