# Verwende den offiziellen Node.js-Image als Basis
FROM node

# Setze das Arbeitsverzeichnis im Container
WORKDIR /portfolio/src

# Kopiere package.json und package-lock.json in das Arbeitsverzeichnis
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den restlichen Projektcode in das Arbeitsverzeichnis
COPY . .

# Starte den Entwicklungsserver
CMD ["npm", "run", "dev"]
